apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-pod-service
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: watchlist-ui
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: watchlist-service
              servicePort: 4000
