apiVersion: apps/v1
kind: Deployment
metadata:
    name: watchlist-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
      app: secure-app
  template:
    metadata:
      labels:
        component: web
        app: secure-app
    spec:
      containers:
        - name: watchlist-ui
          image: rishiwhite11/watchlist-ui:2.2
          ports:
            - containerPort: 3000